// src/lib/components/NotesSearch.svelte
<script lang="ts">
  import { ArrowLeftIcon, XIcon } from '@lucide/svelte';

  import Button from '$lib/components/Button.svelte';
  import Tooltip from '$lib/components/Tooltip.svelte';
  import { search } from '$lib/context/search.svelte';

  function hideSidebarSearch() {
    search.setSidebarOpen(false);
  }

  function handleKeydown(event: KeyboardEvent) {
    if (event.key === 'Escape') {
      hideSidebarSearch();
    }
  }
</script>

<svelte:window onkeydown={handleKeydown} />

<label
  for="notes-search"
  class="flex items-center gap-2 bg-light dark:bg-dark z-50"
>
  <span class="sr-only">Search Notes</span>
  <Tooltip align="start" content="Hide Search">
    <Button
      icon={ArrowLeftIcon}
      iconOnly
      onclick={hideSidebarSearch}
    >
      Hide Search
    </Button>
  </Tooltip>
  <input
    autocomplete="off"
    name="notes-search"
    id="notes-search"
    bind:value={search.value}
    class="block w-full h-full p-0 py-1.5 border-0 border-b-2 border-b-text-gray-400 focus:border-b-white bg-inherit placeholder:text-gray-400 placeholder:select-none focus:ring-0"
    placeholder="Search Notes"
  />
  {#if search.value.length > 0}
    <Button
      icon={XIcon}
      iconOnly
      disabled={!search.value.length}
      onclick={() => search.set('')}
    >
      Clear
    </Button>
  {/if}
</label>

// src/components/NotesSearch/index.tsx
import { useAtom } from 'jotai';
import { SearchIcon, XIcon } from 'lucide-react';

import { Button } from '@/components/Button';
import { notesSearchAtom } from '@/context/notesSearch';
import type { NotesSearchProps } from './types';

export function NotesSearch({
  children,
  name,
}: NotesSearchProps) {
  const [search, setSearch] = useAtom(notesSearchAtom);

  return (
    <label htmlFor={`notes-search-${name}`} className="relative block flex-1">
      <span className="sr-only">Search Notes</span>
      <div className="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-2">
        <SearchIcon className="size-6 text-gray-400" aria-hidden="true" />
      </div>
      <input
        name="notes-search"
        id={`notes-search-${name}`}
        value={search}
        onChange={(event) => setSearch(event.target.value)}
        className="block w-full rounded-lg border-0 py-3 sm:py-2 pl-10 pr-20 bg-inherit outline-offset-1 placeholder:text-gray-400 placeholder:select-none focus-visible"
        placeholder="Search Notes"
      />
      <div className="absolute inset-y-0 right-0">
        {search.length > 0 ? (
          <Button
            Icon={XIcon}
            iconOnly
            disabled={!search.length}
            onClick={() => setSearch('')}
          >
            Clear
          </Button>
        ) : children}
      </div>
    </label>
  );
}
