// src/routes/settings/+page.svelte
<script lang="ts">
  import { GithubIcon } from 'lucide-svelte';

  // import AIcon from '$lib/components/AIcon.svelte';
  import Button from '$lib/components/Button.svelte';
  import Page from '$lib/components/Page.svelte';
  import SettingsAppVersion from '$lib/components/SettingsAppVersion.svelte';
  import SettingsChangeTheme from '$lib/components/SettingsChangeTheme.svelte';
  import SettingsCheckForUpdate from '$lib/components/SettingsCheckForUpdate.svelte';
  import Tooltip from '$lib/components/Tooltip.svelte';
</script>

{#snippet iconsRight()}
  <!-- <Tooltip content="Visit speirs.dev">
    <Button
      icon={AIcon}
      iconOnly
      href="https://speirs.dev"
      target="_blank"
    >
      Visit speirs.dev
    </Button>
  </Tooltip> -->
  <Tooltip content="Visit github.com/afspeirs/note-me">
    <Button
      icon={GithubIcon}
      iconOnly
      href="https://github.com/afspeirs/note-me"
      target="_blank"
    >
      Visit github.com/afspeirs/note-me
    </Button>
  </Tooltip>
{/snippet}

<Page
  title="Settings"
  {iconsRight}
>
  <ul role="list">
    <li>
      <SettingsAppVersion />
      <SettingsCheckForUpdate />
    </li>
    <li aria-hidden="true"><hr class="mx-3 border-gray-300 dark:border-gray-400" /></li>
    <li>
      <SettingsChangeTheme />
    </li>
  </ul>
</Page>

// src/routes/Settings.tsx
import { GithubIcon } from 'lucide-react';

import { AIcon } from '@/components/AIcon';
import { AppVersion } from '@/components/AppVersion';
import { Button } from '@/components/Button';
import { ChangeTheme } from '@/components/ChangeTheme';
import { CheckForUpdate } from '@/components/CheckForUpdate';
import { NotesExport } from '@/components/NotesExport';
import { NotesImport } from '@/components/NotesImport';
import { Page } from '@/components/Page';
import { Tooltip } from '@/components/Tooltip';

export function Settings() {
  return (
    <Page
      title="Settings"
      iconsRight={(
        <>
          <Tooltip content="Visit speirs.dev">
            <Button
              Icon={AIcon}
              iconOnly
              href="https://speirs.dev"
              target="_blank"
            >
              Visit speirs.dev
            </Button>
          </Tooltip>
          <Tooltip content="Visit github.com/afspeirs/note-me">
            <Button
              Icon={GithubIcon}
              iconOnly
              href="https://github.com/afspeirs/note-me"
              target="_blank"
            >
              Visit github.com/afspeirs/note-me
            </Button>
          </Tooltip>
        </>
      )}
    >
      <ul role="list">
        <li>
          <AppVersion />
          <CheckForUpdate />
        </li>
        <li aria-hidden="true"><hr className="mx-3 border-gray-300 dark:border-gray-400" /></li>
        <li>
          <ChangeTheme />
        </li>
        <li aria-hidden="true"><hr className="mx-3 border-gray-300 dark:border-gray-400" /></li>
        <li>
          <NotesImport />
          <NotesExport />
        </li>
      </ul>
    </Page>
  );
}
