// src/lib/components/Card.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import { classNames } from '$lib/utils/classNames';

  type CardProps = {
    // as?: Component,
    children: Snippet,
    class?: string,
    fullscreen?: boolean,
  };

  let {
    // as = 'div',
    children,
    class: className = '',
    fullscreen,
    ...rest
  }: CardProps = $props();
</script>

<div
  class={classNames(
    'bg-light dark:bg-dark dark:text-light shadow',
    fullscreen ? '[@media_not_(display-mode:_browser)]:rounded-t-lg' : 'rounded-lg',
    className,
  )}
  {...rest}
>
  {@render children()}
</div>

// src/components/Card/index.tsx
import { classNames } from '@/utils/classNames';
import type { CardProps } from './types';

export function Card({
  as: Component = 'div',
  children,
  className = '',
  fullscreen,
  ...props
}: CardProps) {
  return (
    <Component
      className={classNames(
        'bg-light dark:bg-dark dark:text-light shadow',
        fullscreen ? '[@media_not_(display-mode:_browser)]:rounded-t-xl' : 'rounded-xl',
        className,
      )}
      {...props} // eslint-disable-line react/jsx-props-no-spreading
    >
      {children}
    </Component>
  );
}
