// src/components/Modal/index.tsx
import { Dialog, Transition } from '@headlessui/react';
import { XIcon } from 'lucide-react';
import { Fragment } from 'react';

import { Button } from '@/components/Button';
import type { ModalProps } from './types';

export function Modal({
  children,
  className,
  onClose,
  open,
  showCloseButton = true,
  theme,
  title,
}: ModalProps) {
  return (
    <Transition show={open} as={Fragment}>
      <Dialog as="div" className="relative z-50" onClose={onClose}>
        <Transition.Child
          as={Fragment}
          enter="ease-out duration-200"
          enterFrom="opacity-0"
          enterTo="opacity-100"
          leave="ease-in duration-200"
          leaveFrom="opacity-100"
          leaveTo="opacity-0"
        >
          <div className="fixed inset-0 bg-primary/70 dark:bg-black/70 backdrop-blur-sm" />
        </Transition.Child>

        <div className={`fixed inset-0 mt-titlebar-area-height overflow-y-auto ${theme}`}>
          <div className="flex min-h-full items-center justify-center p-4 text-center">
            <Transition.Child
              as={Fragment}
              enter="ease-out duration-200"
              enterFrom="opacity-0 scale-95"
              enterTo="opacity-100 scale-100"
              leave="ease-in duration-200"
              leaveFrom="opacity-100 scale-100"
              leaveTo="opacity-0 scale-95"
            >
              <Dialog.Panel className="w-full max-w-md transform overflow-hidden p-5 text-left align-middle transition-all bg-light dark:bg-dark text-dark dark:text-light rounded-xl">
                {showCloseButton && (
                  <Button
                    className="absolute top-2 right-2"
                    Icon={XIcon}
                    iconOnly
                    onClick={onClose}
                  >
                    Close
                  </Button>
                )}

                {title && (
                  <Dialog.Title as="h3" className="mb-6 mr-8 text-xl font-medium">
                    {title}
                  </Dialog.Title>
                )}

                <div className={className}>
                  {children}
                </div>
              </Dialog.Panel>
            </Transition.Child>
          </div>
        </div>
      </Dialog>
    </Transition>
  );
}

// src/lib/components/Modal.svelte
<script lang="ts">
  import { XIcon } from '@lucide/svelte';
  import { onMount, type Snippet } from 'svelte';

  import Button from '$lib/components/Button.svelte';
  import Card from '$lib/components/Card.svelte';
  import Tooltip from '$lib/components/Tooltip.svelte';

  type ModalProps = {
    children: Snippet;
    iconsLeft?: Snippet;
    iconsRight?: Snippet;
    onClose: () => void;
    size?: 'sm' | 'md' | 'lg' | 'xl';
    title?: string | null;
    titleHide?: boolean | null;
  };

  let {
    children,
    iconsLeft,
    iconsRight,
    onClose,
    size = 'md',
    title,
    titleHide = false,
  }: ModalProps = $props();

  let dialogRef = $state<HTMLDialogElement>();

  const sizeClasses = {
    sm: 'max-w-md',
    md: 'max-w-2xl',
    lg: 'max-w-4xl',
    xl: 'max-w-6xl',
  };

  onMount(() => {
    if (dialogRef) dialogRef.showModal();
    return () => {
      if (dialogRef?.open) dialogRef.close();
    };
  });

  function handleClick(event: MouseEvent) {
    if (dialogRef && event.target === dialogRef) {
      onClose();
    }
  }
</script>

<Card
  bind:ref={dialogRef}
  as="dialog"
  onclick={handleClick}
  oncancel={(event) => {
    event.preventDefault();
    onClose();
  }}
  class="fixed inset-0 m-auto border-none p-0 w-full max-h-[90vh] overflow-auto pointer-events-auto {sizeClasses[size]} open:animate-modal-show backdrop:animate-backdrop-show backdrop:bg-primary/70 dark:backdrop:bg-black/70 backdrop:backdrop-blur-sm"
>
  <header class="relative flex gap-card-gap p-card-gap">
    {#if !titleHide}
      <div class="ml-2 self-center font-bold text-xl truncate select-none">{title}</div>
    {/if}

    {@render iconsLeft?.()}

    <div class="ml-auto"></div>

    {@render iconsRight?.()}

    <Tooltip align="end" content="Close">
      <Button
        icon={XIcon}
        iconOnly
        onclick={onClose}
      >
        Close
      </Button>
    </Tooltip>
  </header>

  {@render children()}
</Card>
