// src/components/Page.tsx
import { ReactNode } from 'react';
import { Helmet } from 'react-helmet';
import { useAtom } from 'jotai';
import {
  Bars2Icon,
  ChevronLeftIcon,
} from '@heroicons/react/24/solid';

import { ButtonIcon } from './ButtonIcon';
import { drawerOpen } from '../context/navigation';

export interface PageProps {
  children: ReactNode,
  icons?: ReactNode,
  title?: string,
}

export function Page({
  children,
  icons,
  title,
}: PageProps) {
  const [open, setOpen] = useAtom(drawerOpen);

  return (
    <>
      <Helmet>
        <title>{`${title ? `${title} | ` : ''}NoteMe`}</title>
      </Helmet>

      <header className="flex gap-2 p-2">
        <ButtonIcon
          className="mr-auto"
          Icon={open ? ChevronLeftIcon : Bars2Icon}
          label={`${open ? 'Close' : 'Open'} Sidebar`}
          onClick={() => setOpen((prevState) => !prevState)}
        />
        {icons}
      </header>
      <main className="flex-1 px-4 pt-1 overflow-y-auto">
        {children}
      </main>
    </>
  );
}

// src/lib/components/Page.svelte
<script lang="ts">
  import { MenuIcon } from 'lucide-svelte';
  import type { Snippet } from 'svelte';

  import Button from '$lib/components/Button.svelte';
  import Tooltip from '$lib/components/Tooltip.svelte';
  import { sidebarOpen } from '$lib/context/navigation.svelte';

  function toggleSidebarOpen() {
    sidebarOpen.toggle();
  }

  type PageProps = {
    children: Snippet,
    iconsLeft?: Snippet,
    iconsRight?: Snippet,
    title?: string | null,
    titleHide?: boolean | null,
  };

  let {
    children,
    iconsLeft,
    iconsRight,
    title,
    titleHide = false,
  }: PageProps = $props();
</script>

<svelte:head>
  <title>{title && title !== 'NoteMe' ? `${title} | ` : ''}NoteMe</title>
</svelte:head>

<header class="relative flex gap-card-gap p-card-gap">
  <Tooltip content={`${sidebarOpen.value ? 'Close' : 'Open'} Sidebar`}>
    <Button
      icon={MenuIcon}
      iconOnly
      onclick={toggleSidebarOpen}
    >
      {`${sidebarOpen.value ? 'Close' : 'Open'} Sidebar`}
    </Button>
  </Tooltip>

  {#if !titleHide}
    <div class="ml-2 self-center font-bold text-xl truncate select-none">{title}</div>
  {/if}

  {@render iconsLeft?.()}

  <div class="ml-auto"></div>

  {@render iconsRight?.()}
</header>

<main class="flex-1 overflow-auto">
  {@render children()}
</main>
